meta:
  engine: 4.1.0
  version: 0.0.1
  author: n1tsu

units:
  # keys
  keycaps_size: 16
  keycaps_padding: 1
  keycap_dist: keycaps_size+keycaps_padding
  kd: keycaps_size+keycaps_padding
  qcol_stagger: 0kd
  wcol_stagger: 0kd
  ecol_stagger: 0kd
  rcol_stagger: -0kd
  tcol_stagger: -0kd
  ycol_stagger: -0kd
  thumb_splay: 15

  # BOARD
  bp_t: 32.4
  bp_b: 8 + 5.2
  bp_r: 8 + 5.2
  bp_l: 8 + 5.2
  # case
  case_edge_size: 0

  # components
  components_padding: 4
  nicenano_width: 19.05
  nicenano_height: 21
  ctype_height: 1.53
  ctype_width: 8.95
  battery_width: 70
  battery_height: 20
  battery_connector_width: 8.275 # !
  battery_connector_height: 3.475 # !
  power_width: 8.425
  power_height: 4.275
  power_button_size: 1.5
  reset_width: 4.5
  reset_height: 6.4

  #components_loc
  # controller_rel_x: 3*kd+20
  # controller_rel_y: bp_t - nicenano_height * 0.5
  # controller_rot: 90
  #
  # battery_rel_x: kd+20
  # battery_rel_y: -7
  # battery_rot: 90

  controller_rel_x: -32
  controller_rel_y: bp_t - nicenano_height * 0.5  -0.7
  controller_rot: 0

  battery_rel_x: -17
  battery_rel_y: 2kd+bp_t - nicenano_width * 0.5 -2
  battery_rot: 90

  # power_rel_x: controller_rel_x + power_width + 7
  power_rel_x: 3*keycap_dist + bp_r - 0.5 power_height+ 0.338
  power_rel_y: 20
  power_rot: -90

  battery_connector_rel_x: 3*keycap_dist + bp_r - 1.5 power_height
  battery_connector_rel_y: 20
  battery_connector_rot: -90

points:
  zones:
    matrix:
      key:
        spread: keycaps_size + keycaps_padding
        tags: "keys"
      anchor.shift: [50, -100]
      columns:
        qcolumn.key:
          stagger: qcol_stagger
          column_net: P0
          mirror.column_net: P0r
        wcolumn.key:
          stagger: wcol_stagger
          column_net: P1
          mirror.column_net: P1r
        ecolumn.key:
          stagger: ecol_stagger
          column_net: P2
          mirror.column_net: P2r
        rcolumn.key:
          stagger: rcol_stagger
          column_net: P3
          mirror.column_net: P3r
        tcolumn.key:
          stagger: tcol_stagger
          column_net: P4
          mirror.column_net: P4r
        ycolumn.key:
          stagger: ycol_stagger
          column_net: P5
          mirror.column_net: P5r
        # ycolumn.key.mirror.column_net: P0
      rows:
        thumb_row:
          padding: keycap_dist
          row_net: P10
          mirror.row_net: P10r
        zrow:
          padding: keycaps_size + keycaps_padding
          row_net: P9
          mirror.row_net: P9r
        arow:
          padding: keycaps_size + keycaps_padding
          row_net: P8
          mirror.row_net: P8r
        qrow:
          padding: keycaps_size + keycaps_padding
          row_net: P7
          mirror.row_net: P7r

    mounting_hole_lt:
      key.tags:
        - screw
      anchor:
        ref: matrix_qcolumn_qrow
        shift: [-bp_l + 2.1, bp_t - 2.1]

    mounting_hole_lb:
      key.tags:
        - screw
      anchor:
        ref: matrix_qcolumn_thumb_row
        shift: [-bp_l + 2.1, -5.1]

    mounting_hole_rt:
      key.tags:
        - screw
      anchor:
        ref: matrix_ycolumn_qrow
        shift: [bp_l-2.1, bp_t - 2.1]

    mounting_hole_rb:
      key.tags:
        - screw
      anchor:
        ref: matrix_ycolumn_thumb_row
        shift: [bp_l - 2.1, -5.1]

    # mounting_hole_mt:
    #   key.tags:
    #     - screw
    #   anchor:
    #     ref: matrix_ecolumn_qrow
    #     shift: [8.5, bp_t-2.1]
    # mounting_hole_mb:
    #   key.tags:
    #     - screw
    #   anchor:
    #     ref: matrix_ecolumn_thumb_row
    #     shift: [8.5, -11.1]

    controller:
      anchor:
        ref: matrix_ecolumn_qrow
        shift: [controller_rel_x, controller_rel_y]
        rotate: controller_rot

    ctype:
      anchor:
        ref: controller
        shift: [0, 0.5 nicenano_height + 0.5 ctype_height]

    battery:
      anchor:
        ref: matrix_tcolumn_zrow
        shift: [battery_rel_x, battery_rel_y]
        rotate: 90

    power:
      anchor:
        ref: matrix_ecolumn_qrow
        shift: [power_rel_x, power_rel_y+0.5]
        rotate: power_rot

    battery_connector:
      anchor:
        ref: matrix_ecolumn_qrow
        shift: [battery_connector_rel_x, battery_connector_rel_y]
        rotate: battery_connector_rot

  mirror:
    ref: matrix_rcolumn_arow
    distance: 140

outlines:
  keycaps:
    - what: rectangle
      where: keys
      size: keycaps_size
      asym: both

  # BOARD OUTLINE
  board:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_ecolumn_qrow
          shift: [-2*keycap_dist -bp_l, bp_t]
        - ref: matrix_ecolumn_qrow
          shift: [3*keycap_dist+bp_r, bp_t]
        - ref: matrix_ecolumn_zrow
          shift:
            [3*keycap_dist+bp_r, rcol_stagger+  tcol_stagger - keycap_dist-bp_b]
        - ref: matrix_ecolumn_zrow
          shift:
            [
              -2*keycap_dist- bp_l,
              rcol_stagger+  tcol_stagger - keycap_dist -bp_b,
            ]
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: mirror_matrix_ecolumn_qrow
          shift: [-2*keycap_dist -bp_l, bp_t]
        - ref: mirror_matrix_ecolumn_qrow
          shift: [3*keycap_dist+bp_r, bp_t]
        - ref: mirror_matrix_ecolumn_zrow
          shift:
            [3*keycap_dist+bp_r, rcol_stagger+  tcol_stagger - keycap_dist-bp_b]
        - ref: mirror_matrix_ecolumn_zrow
          shift:
            [
              -2*keycap_dist- bp_l,
              rcol_stagger+  tcol_stagger - keycap_dist -bp_b,
            ]

  controller:
    - what: rectangle
      where: controller
      size: [nicenano_width, nicenano_height]
      asym: both
      # adjust.rotate: controller_rot

  ctype:
    - what: rectangle
      where: ctype
      size: [ctype_width, ctype_height]
      asym: both

  battery:
    - what: rectangle
      where: battery
      size: [battery_width, battery_height]
      asym: both
      adjust.rotate: battery_rot

  power_switch:
    - what: rectangle
      where: power
      size: [power_width, power_height]
      asym: both

  battery_connector:
    - what: rectangle
      where: battery_connector
      size: [battery_connector_width, battery_connector_height]
      asym: both

  screws:
    - what: circle
      where: screw
      radius: 1.1

  combo:
    - operation: stack
      name: keycaps
    - operation: stack
      name: board
    - operation: stack
      name: controller
    - operation: stack
      name: ctype
    - operation: stack
      name: battery
    - operation: stack
      name: power_switch
    - operation: stack
      name: battery_connector
    - operation: stack
      name: screws

  combo2:
    - operation: stack
      name: keycaps
    - operation: stack
      name: board
    # - operation: stack
    #   name: controller
    # - operation: stack
    #   name: battery
  pcb_outline:
    - operation: stack
      name: board
    - operation: stack
      name: screws

pcbs:
  main_pcb:
    outlines:
      main:
        outline: pcb_outline

      # battery:
      #   outline: battery
      #   layer: "F.SilkS"

    template: kicad8
    footprints:
      switch:
        what: pg1316s
        where: keys
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"

      diodes_left:
        what: diode_tht_sod123
        where: /^matrix_.*|^thumb_.*/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0.3, 2.4]
          rotate: 180

      diodes_right:
        what: diode_tht_sod123
        where: /^mirror_matrix_.*|^mirror_thumb_.*/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-0.3, 2.4]
          rotate: 180

      # controller footprints isn't mirrored

      controller_left:
        what: xiao_ble
        # params:
        #   P0: P0_l
        where: controller

      controller_right:
        what: xiao_ble
        params:
          VIN: VINr
          SWDIO: SWDIO7
          SWDCLK: SWDCLKr
          RST: RSTr
          GND: GNDr
          P0: P0r
          P1: P1r
          P2: P2r
          P3: P3r
          P4: P4r
          P5: P5r
          P6: P6r
          P7: P7r
          P8: P8r
          P9: P9r
          P10: P10r
          RAW3V3: RAW3V3r
          RAW5V: RAW5Vr
        where: mirror_controller

      battery_connector_left:
        what: battery_pad
        params:
          plus: BAT_P
          minus: GND
        where: battery_connector

      battery_connector_right:
        what: battery_pad
        params:
          plus: BAT_Pr
          minus: GNDr
        where: mirror_battery_connector
        adjust.rotate: 180

      power_left:
        what: power_switch_smd_side
        params:
          to: VIN
        where: power
        adjust.rotate: 90

      power_right:
        what: power_switch_smd_side
        params:
          from: BAT_Pr
          to: VINr
          invert_behavior: false
        where: mirror_power
        adjust.rotate: -90

      #   params:
      #     orientation: up
      #   # PCB controller is 90 oriented by default
      #   adjust.rotate: -90 + controller_rotation
      # controller_right:
      #   what: nicenano
      #   where: mirror_controller
      #   params:
      #     orientation: up
      #   # PCB controller is 90 oriented by default
      #   # PCB controller is 90 oriented by default
      #   adjust.rotate: -90 + controller_rotation + 180
      #

      # reset:
      #   what: reset_switch_smd_side
      #   where: reset
      #   params:
      #     include_bosses: true
      #   asym: both
      #   adjust.rotate: reset_rotation
      #
      # holes:
      #   what: mounting_hole_plated
      #   where: holes
      #
      # text:
      #   what: utility_text
      #   where: text
      #   asym: both
      #   params:
      #     side: "F"
      #     mirrored: false
      #     text: "n36tsu v0.1.0"
